name: ctf1
on:
  pull_request_target:
jobs:
  ctf1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge
      - name: run tests
        run: make test
        env:
          EXAMPLE_SECRET: ${{ secrets.EXAMPLE_SECRET }}
        
